#!/usr/bin/env bash
# bootstrap.sh — One-command Fleetwright setup
# Usage: bash scripts/bootstrap.sh [--no-docker] [--no-start]
set -euo pipefail

# ── Colour helpers ────────────────────────────────────────────────────────────
if [ -t 1 ] && command -v tput &>/dev/null; then
  _GREEN=$(tput setaf 2); _YELLOW=$(tput setaf 3); _RED=$(tput setaf 1)
  _BOLD=$(tput bold); _RESET=$(tput sgr0)
else
  _GREEN=""; _YELLOW=""; _RED=""; _BOLD=""; _RESET=""
fi

green()  { printf "%s%s%s\n"  "$_GREEN"  "$*" "$_RESET"; }
yellow() { printf "%s%s%s\n"  "$_YELLOW" "$*" "$_RESET"; }
red()    { printf "%s%s%s\n"  "$_RED"    "$*" "$_RESET"; }
bold()   { printf "%s%s%s\n"  "$_BOLD"   "$*" "$_RESET"; }
die()    { red "ERROR: $*" >&2; exit 1; }

# ── Step counter ──────────────────────────────────────────────────────────────
_STEP=0
step() {
  _STEP=$(( _STEP + 1 ))
  bold "[$_STEP] $*"
}

# ── Flags ─────────────────────────────────────────────────────────────────────
NO_DOCKER=0
NO_START=0
for arg in "$@"; do
  case "$arg" in
    --no-docker) NO_DOCKER=1 ;;
    --no-start)  NO_START=1  ;;
    *) die "Unknown argument: $arg  (supported: --no-docker --no-start)" ;;
  esac
done

# ── Locate repo root ──────────────────────────────────────────────────────────
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
cd "$REPO_ROOT"

bold ""
bold "========================================"
bold "  Fleetwright bootstrap"
bold "  $(pwd)"
bold "========================================"
echo ""

# ── Port config ───────────────────────────────────────────────────────────────
BRIDGE_PORT="${BRIDGE_PORT:-8787}"
COCKPIT_PORT="${COCKPIT_PORT:-3131}"

# ── Prerequisite checks ───────────────────────────────────────────────────────
step "Checking prerequisites"

# Python version
if ! command -v python3 &>/dev/null; then
  die "python3 not found. Install Python 3.11+ from https://www.python.org/downloads/"
fi

PYTHON_VERSION="$(python3 -c 'import sys; print(f"{sys.version_info.major}.{sys.version_info.minor}")')"
PYTHON_MAJOR="${PYTHON_VERSION%%.*}"
PYTHON_MINOR="${PYTHON_VERSION#*.}"
if [ "$PYTHON_MAJOR" -lt 3 ] || { [ "$PYTHON_MAJOR" -eq 3 ] && [ "$PYTHON_MINOR" -lt 11 ]; }; then
  die "Python 3.11+ required (found $PYTHON_VERSION). Install a newer Python and try again."
fi
green "  Python $PYTHON_VERSION — OK"

# git
if ! command -v git &>/dev/null; then
  die "git not found. Install git from https://git-scm.com/"
fi
green "  git — OK"

# claude CLI
CLAUDE_FOUND=0
for candidate in /opt/homebrew/bin/claude "$HOME/.claude/local/claude" /usr/local/bin/claude; do
  if [ -x "$candidate" ]; then
    CLAUDE_BIN="$candidate"
    CLAUDE_FOUND=1
    break
  fi
done
if [ "$CLAUDE_FOUND" -eq 0 ] && command -v claude &>/dev/null; then
  CLAUDE_BIN="$(command -v claude)"
  CLAUDE_FOUND=1
fi

if [ "$CLAUDE_FOUND" -eq 0 ]; then
  echo ""
  yellow "  WARNING: claude CLI not found."
  yellow "  Fleetwright requires the Claude Code CLI with an active subscription."
  yellow "  Install it from: https://claude.ai/code"
  yellow "  Then run 'claude' once to authenticate before using Fleetwright."
  echo ""
else
  green "  claude CLI — $CLAUDE_BIN"
fi

# Docker (optional)
DOCKER_OK=0
if [ "$NO_DOCKER" -eq 0 ]; then
  if command -v docker &>/dev/null && docker info &>/dev/null 2>&1; then
    DOCKER_OK=1
    green "  Docker — OK"
  else
    yellow "  Docker not available (skipping db + cockpit containers; run bridge only)"
    NO_DOCKER=1
  fi
fi

echo ""

# ── .env setup ────────────────────────────────────────────────────────────────
step "Configuring environment"

if [ ! -f "$REPO_ROOT/.env" ]; then
  if [ -f "$REPO_ROOT/.env.example" ]; then
    cp "$REPO_ROOT/.env.example" "$REPO_ROOT/.env"
    green "  Created .env from .env.example"
  else
    yellow "  No .env.example found — creating minimal .env"
    cat > "$REPO_ROOT/.env" <<'ENVEOF'
# Fleetwright environment — generated by bootstrap.sh
BRIDGE_SECRET=change-me-generate-with-openssl-rand-hex-32
ENVEOF
  fi
else
  green "  .env already exists — leaving untouched"
fi

# Generate BRIDGE_SECRET if it's still the placeholder
CURRENT_SECRET="$(grep -E '^BRIDGE_SECRET=' "$REPO_ROOT/.env" | cut -d= -f2- | tr -d '"' | tr -d "'" | xargs 2>/dev/null || true)"
if [ "$CURRENT_SECRET" = "change-me-generate-with-openssl-rand-hex-32" ] || [ -z "$CURRENT_SECRET" ]; then
  # Try openssl first, fall back to python
  if command -v openssl &>/dev/null; then
    NEW_SECRET="$(openssl rand -hex 32)"
  else
    NEW_SECRET="$(python3 -c 'import secrets; print(secrets.token_hex(32))')"
  fi
  # Replace in-place (portable sed for macOS + Linux)
  if [ "$(uname)" = "Darwin" ]; then
    sed -i '' "s|^BRIDGE_SECRET=.*|BRIDGE_SECRET=${NEW_SECRET}|" "$REPO_ROOT/.env"
  else
    sed -i "s|^BRIDGE_SECRET=.*|BRIDGE_SECRET=${NEW_SECRET}|" "$REPO_ROOT/.env"
  fi
  green "  Generated BRIDGE_SECRET"
else
  green "  BRIDGE_SECRET already set"
fi

echo ""

# ── Python package install ────────────────────────────────────────────────────
step "Installing Fleetwright Python package"
python3 -m pip install --quiet -e "$REPO_ROOT"
green "  Installed fleetwright (editable)"
echo ""

# ── ~/.fleetwright directory structure ───────────────────────────────────────
step "Creating ~/.fleetwright directory structure"
FW_ROOT="${FLEETWRIGHT_ROOT:-$HOME/.fleetwright}"
mkdir -p \
  "$FW_ROOT/state" \
  "$FW_ROOT/logs/runs" \
  "$FW_ROOT/logs/bridge" \
  "$FW_ROOT/.fleet-worktrees"
green "  $FW_ROOT — OK"
echo ""

# ── domains.yaml ─────────────────────────────────────────────────────────────
step "Configuring domains"
if [ -f "$REPO_ROOT/config/domains.yaml" ]; then
  green "  config/domains.yaml already exists — leaving untouched"
elif [ -f "$REPO_ROOT/config/domains.example.yaml" ]; then
  cp "$REPO_ROOT/config/domains.example.yaml" "$REPO_ROOT/config/domains.yaml"
  green "  Created config/domains.yaml from domains.example.yaml"
else
  yellow "  No domains.example.yaml found — skipping (create config/domains.yaml manually)"
fi
echo ""

# ── Docker services ───────────────────────────────────────────────────────────
if [ "$NO_DOCKER" -eq 0 ]; then
  step "Starting Docker services (db + cockpit)"
  docker compose -f "$REPO_ROOT/docker-compose.yml" up -d db cockpit
  green "  db + cockpit started"
  echo ""
fi

# ── Bridge ────────────────────────────────────────────────────────────────────
if [ "$NO_START" -eq 0 ]; then
  step "Starting Fleetwright bridge"

  # Check if already running
  if curl -sf "http://127.0.0.1:${BRIDGE_PORT}/health" &>/dev/null; then
    yellow "  Bridge already running on port $BRIDGE_PORT — skipping start"
  else
    # Source .env so bridge picks up config
    set -o allexport
    # shellcheck disable=SC1091
    [ -f "$REPO_ROOT/.env" ] && source "$REPO_ROOT/.env"
    set +o allexport

    LOG_FILE="$FW_ROOT/logs/bridge/bridge.log"
    nohup fleetwright-bridge --host 127.0.0.1 --port "$BRIDGE_PORT" \
      > "$LOG_FILE" 2>&1 &
    BRIDGE_PID=$!
    echo "$BRIDGE_PID" > "$FW_ROOT/bridge.pid"

    # Wait for it to come up (up to 10s)
    READY=0
    for i in $(seq 1 20); do
      if curl -sf "http://127.0.0.1:${BRIDGE_PORT}/health" &>/dev/null; then
        READY=1
        break
      fi
      sleep 0.5
    done

    if [ "$READY" -eq 1 ]; then
      green "  Bridge started (pid $BRIDGE_PID) — http://localhost:${BRIDGE_PORT}"
    else
      yellow "  Bridge may still be starting. Check logs: tail -f $LOG_FILE"
    fi
  fi
  echo ""
fi

# ── Summary ───────────────────────────────────────────────────────────────────
bold "========================================"
bold "  Fleetwright setup complete"
bold "========================================"
echo ""
green "  Bridge:  http://localhost:${BRIDGE_PORT}"
if [ "$NO_DOCKER" -eq 0 ]; then
  green "  Cockpit: http://localhost:${COCKPIT_PORT}"
fi
echo ""
bold "Next steps:"
echo "  1. Verify:  curl http://localhost:${BRIDGE_PORT}/health"
if [ "$NO_DOCKER" -eq 0 ]; then
  echo "  2. Open:    http://localhost:${COCKPIT_PORT}"
fi
echo ""
bold "To stop:"
if [ "$NO_DOCKER" -eq 0 ]; then
  echo "  docker compose down"
fi
PID_FILE="$FW_ROOT/bridge.pid"
if [ -f "$PID_FILE" ]; then
  echo "  kill \$(cat $PID_FILE)  # stop bridge"
fi
echo ""
